service: serverless-aws-emr-api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  getWeather:
    handler: lambdas/weatherData.handler
    events:
      - http:
          path: weatherdata/{CITY}
          method: GET
          cors: true
