service: serverless-weather
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  profile: slss_weather

functions:
  getWeather:
    handler: lambdas/weatherData.handler
    events:
      - http:
          path: weatherdata/{ID}
          method: GET
          cors: true
